import {useEffect,useMemo,useRef,useState} from 'react';
import type {DataBundle} from './types';
import {href} from './router';
import {NodeLink,TypeBadge} from './ui';
import {GUIDED_RESPONSES,guidedResponseLabels} from '../guided/runtime';
import {networkLayout,networkLinks,projectWalk,validWalk,type WalkEvent} from '../guided/network';
import './network.css';

const colors:Record<string,string>={claim:'#69b6ff',source:'#44e4ce',receipt:'#44e4ce',observation:'#74dac6',measurement:'#7bddf8',derivation:'#7bddf8',assumption:'#ffb37b',burden:'#ffc46a',diagnostic:'#ff758b',ratchet:'#b79aff',lock:'#b79aff',theory:'#e3adf2',method:'#92b7c0',escape:'#8490a9'};
const key='epicenter.network.walk.v1';
const starters=['rat-itd-nearfield','rat-4940-provenance','rat-pcb-dimensions','rat-pcb-color','rat-radial-pressure','rat-13of13-meaning'];
export function NetworkExperience({bundle,focusParam}:{bundle:DataBundle;focusParam?:string}){
 const nodes=useMemo(()=>new Map(bundle.graph.nodes.map(n=>[n.id,n])),[bundle]);
 const [selected,setSelected]=useState(nodes.has(focusParam??'')?focusParam!:'clm-petn-shaped-charge-hidden');
 const [events,setEvents]=useState<WalkEvent[]>(()=>{try{const v=JSON.parse(localStorage.getItem(key)??'null');return validWalk(v,bundle)?v.events:[]}catch{return []}});
 const [storageError,setStorageError]=useState('');const [query,setQuery]=useState('');const [layer,setLayer]=useState('all');
 const [ratchet,setRatchet]=useState(()=>{const e=[...events].reverse().find(e=>e.kind==='answer');return e?.kind==='answer'?e.ratchet:''});const [mode,setMode]=useState<'case'|'ratchet'>(events.some(e=>e.kind==='answer')?'ratchet':'case');const [edge,setEdge]=useState<string>();
 const [note,setNote]=useState('');const [view,setView]=useState({x:0,y:0,z:1});
 const [dragged,setDragged]=useState<Record<string,{x:number;y:number}>>({});
 const svg=useRef<SVGSVGElement>(null);const drag=useRef<{id?:string;x:number;y:number;ox:number;oy:number;moving:boolean}|undefined>(undefined);
 const importRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify({build:bundle.graph.build_id,events}));setStorageError('')}catch{setStorageError('Browser storage unavailable. Export your walk to keep it.')}},[events,bundle.graph.build_id]);
 useEffect(()=>{if(focusParam&&nodes.has(focusParam)){setSelected(focusParam);setEdge(undefined)}},[focusParam,nodes]);
 const projection=useMemo(()=>projectWalk(bundle,events),[bundle,events]);
 const allLinks=useMemo(()=>networkLinks(bundle),[bundle]);
 const r=nodes.get(ratchet);const lastAnswer=[...events].reverse().find(e=>e.kind==='answer'&&e.ratchet===ratchet);
 const lockId=lastAnswer?.kind==='answer'?(lastAnswer.response==='tangent'?lastAnswer.lock:nodes.get(lastAnswer.lock)?.branches?.[lastAnswer.response]):r?.entry_lock;
 const lock=nodes.get(lockId);const selectedNode=nodes.get(selected)!;
 const relatedRatchets=bundle.graph.nodes.filter(n=>n.type==='ratchet'&&(bundle.topology.ratchets[n.id]?.targets??[]).includes(selected));
 const ratchetIds=new Set<string>([...(r?.locks??[]),...(r?.convergence??[])]);
 for(const id of r?.locks??[])for(const b of nodes.get(id)?.burdens??[])ratchetIds.add(b);
 const visibleNodes=bundle.graph.nodes.filter(n=>mode==='ratchet'?ratchetIds.has(n.id):layer==='all'||(layer==='argument'?!['lock','ratchet','escape'].includes(n.type):['source','receipt','observation','measurement','derivation','assumption','claim'].includes(n.type)));
 const visibleIds=new Set(visibleNodes.map(n=>n.id));
 const links=allLinks.filter(l=>visibleIds.has(l.from)&&visibleIds.has(l.to)&&(mode==='ratchet'||l.kind!=='branch'));
 const layout=useMemo(()=>networkLayout({...bundle,graph:{...bundle.graph,nodes:visibleNodes}},links),[bundle,mode,ratchet,layer]);
 const pos=(id:string)=>dragged[id]??layout[id];
 const neighbor=new Set([selected,lockId,...(lock?.targets??[]),...(lock?.burdens??[])]);
 for(const l of links)if(l.from===selected||l.to===selected){neighbor.add(l.from);neighbor.add(l.to)}
 const support=projection.support.get(selected);
 const activeBurdens=[...new Set([...projection.burdens,...(lock?.burdens??[]),...(lock?.targets??[]).flatMap((id:string)=>bundle.topology.claim_state[id]?.all_burdens??[]),...(r?.convergence??[])])].filter(id=>nodes.get(id)?.type==='burden');
 const results=query.trim()?bundle.graph.nodes.filter(n=>`${n.title} ${n.id}`.toLowerCase().includes(query.toLowerCase())).slice(0,12):[];
 function select(id:string){setSelected(id);setEdge(undefined)}
 function launch(id:string){setRatchet(id);setMode('ratchet');setView({x:0,y:0,z:1});setDragged({});const target=nodes.get(id);select(target?.entry_lock??selected)}
 function append(e:WalkEvent){setEvents(v=>[...v,e])}
 function reset(){setEvents([]);setNote('');setView({x:0,y:0,z:1});setDragged({})}
 function exportWalk(){const url=URL.createObjectURL(new Blob([JSON.stringify({build:bundle.graph.build_id,events},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='epicenter-local-walk.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const point=(e:{clientX:number;clientY:number})=>{const p=svg.current!.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const mapped=p.matrixTransform(svg.current!.getScreenCTM()!.inverse());return {x:mapped.x,y:mapped.y}};
 const edgeInfo=allLinks.find(l=>l.id===edge);const sourceEdge=bundle.graph.edges.find(e=>e.id===edge);
 const branchGroups=links.filter(l=>l.kind==='branch').reduce((m,l)=>{const id=l.from+'|'+l.to;const old=m.get(id);if(old)old.label+=' / '+l.label;else m.set(id,{...l});return m},new Map<string,typeof links[number]>());
 const drawn=[...links.filter(l=>l.kind!=='branch'),...branchGroups.values()];
 const changedClaims=[...projection.paths.keys()].filter(id=>nodes.get(id)?.type==='claim'&&!projection.withheld.has(id));
 return <main className="network-page">
  <header className="network-head"><div><p className="network-kicker">FOLLOW THE EPICENTER / ARGUMENT EXPLORER</p><h1>Pull a thread. Follow what changes.</h1></div><div className="network-session"><span className="live-dot"/> LOCAL WHAT-IF <button onClick={exportWalk}>Export</button><button onClick={()=>importRef.current?.click()}>Import</button><button onClick={reset}>Reset walk</button><input ref={importRef} hidden type="file" accept=".json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{const v=JSON.parse(await f.text());if(!validWalk(v,bundle))throw Error('This walk is invalid or belongs to a different graph build.');setEvents(v.events);setStorageError('')}catch(err){setStorageError(String(err))}e.target.value=''}}/></div></header>
  {storageError&&<p role="alert" className="network-alert">{storageError}</p>}
  <div className="network-workspace">
   <aside className="network-library"><p className="network-kicker">FIND A THREAD</p><input aria-label="Find a graph node" placeholder="Search claims, evidence…" value={query} onChange={e=>setQuery(e.target.value)}/>{results.length>0&&<div className="network-results">{results.map(n=><button key={n.id} onClick={()=>{select(n.id);setMode('case');setLayer('all');setQuery('')}}><TypeBadge type={n.type}/>{n.title}</button>)}</div>}
    <h2>Start an examination</h2>{starters.map((id,i)=><button className={`network-case ${ratchet===id?'chosen':''}`} key={id} onClick={()=>launch(id)}><span>0{i+1}</span><strong>{nodes.get(id)?.title}</strong><b>↗</b></button>)}
    <label className="network-more">All {bundle.graph.nodes.filter(n=>n.type==='ratchet').length} ratchets<select aria-label="Choose a ratchet" value={ratchet} onChange={e=>launch(e.target.value)}><option value="" disabled>Choose an examination</option>{bundle.graph.nodes.filter(n=>n.type==='ratchet').map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label>
    <div className="network-legend"><h2>Read the network</h2>{['claim','source','measurement','assumption','burden','lock'].map(t=><span key={t}><i style={{background:colors[t]}}/>{t==='lock'?'Question / lock':t}</span>)}<p>Solid: authored relationship<br/>Dashed: provenance / field reference<br/>Purple: answer branch</p><p>Amber halo: dependency affected<br/>Hollow: premise withheld locally</p></div>
   </aside>
   <section className="network-stage" aria-label="Interactive argument network">
    <div className="network-canvas-toolbar"><div><button className={mode==='case'?'active':''} onClick={()=>{setMode('case');setView({x:0,y:0,z:1});setDragged({})}}>Case network</button><button disabled={!ratchet} className={mode==='ratchet'?'active':''} onClick={()=>{setMode('ratchet');setView({x:0,y:0,z:1});setDragged({})}}>Ratchet paths</button></div><select aria-label="Network layer" value={layer} disabled={mode==='ratchet'} onChange={e=>{setLayer(e.target.value);setDragged({})}}><option value="all">All node types</option><option value="argument">Argument & evidence</option><option value="evidence">Evidence chain</option></select></div>
    <div className="network-map-caption"><strong>{mode==='ratchet'?r?.title:'The published case'}</strong><span>{visibleNodes.length} nodes · {links.length} connections</span><small>{mode==='ratchet'?'Branches reconverge on unresolved obligations.':'Authored relationships, field references, and compiled provenance.'}</small></div>
    <svg ref={svg} viewBox="0 0 1200 840" preserveAspectRatio="xMidYMid meet" aria-label="Claim and ratchet graph" onWheel={e=>{const p=point(e);setView(v=>{const z=Math.max(.45,Math.min(4,v.z*(e.deltaY<0?1.12:.89)));return {z,x:p.x-(p.x-v.x)*z/v.z,y:p.y-(p.y-v.y)*z/v.z}})}} onPointerDown={e=>{if(e.target===e.currentTarget){const p=point(e);drag.current={...p,ox:view.x,oy:view.y,moving:false};e.currentTarget.setPointerCapture(e.pointerId)}}} onPointerMove={e=>{if(!drag.current)return;const p=point(e),d=drag.current;const dx=p.x-d.x,dy=p.y-d.y;if(Math.abs(dx)+Math.abs(dy)>3)d.moving=true;if(d.id)setDragged(v=>({...v,[d.id!]:{x:d.ox+dx/view.z,y:d.oy+dy/view.z}}));else setView(v=>({...v,x:d.ox+dx,y:d.oy+dy}))}} onPointerUp={()=>{drag.current=undefined}} onPointerCancel={()=>{drag.current=undefined}}>
     <defs><radialGradient id="networkGlow"><stop stopColor="#123243"/><stop offset="1" stopColor="#080f17"/></radialGradient><marker id="networkArrow" viewBox="0 0 10 10" refX="20" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L10 5L0 10" fill="#9cacbc"/></marker></defs>
     <g transform={`translate(${view.x} ${view.y}) scale(${view.z})`}>
      {drawn.map(l=>{const a=pos(l.from),b=pos(l.to);if(!a||!b)return null;const near=l.from===selected||l.to===selected;const affected=projection.paths.has(l.from)||projection.paths.has(l.to);const taken=l.kind==='branch'&&events.some(e=>e.kind==='answer'&&e.lock===l.from&&nodes.get(e.lock)?.branches?.[e.response]===l.to);const self=l.from===l.to;const d=self?`M${a.x-7} ${a.y-7} C${a.x-65} ${a.y-90} ${a.x+65} ${a.y-90} ${a.x+7} ${a.y-7}`:`M${a.x} ${a.y} Q${(a.x+b.x)/2+14} ${(a.y+b.y)/2-22} ${b.x} ${b.y}`;return <g key={l.id} className={`network-edge ${near?'near':''} ${affected?'affected':''} ${taken?'taken':''} ${l.kind}`}><path d={d} markerEnd={mode==='ratchet'||near?'url(#networkArrow)':undefined} onClick={()=>setEdge(l.id)}><title>{nodes.get(l.from)?.title} → {l.label} → {nodes.get(l.to)?.title}</title></path>{(near&&view.z>1.2||l.kind==='branch')&&<text x={self?a.x:(a.x+b.x)/2+14} textAnchor="middle" y={self?a.y-65:(a.y+b.y)/2-20}>{l.kind==='branch'&&l.label.split(' / ').length===7?'all responses · return':l.label.replaceAll('_',' ')}</text>}</g>})}
      {[...visibleNodes].sort((a,b)=>Number(a.id===selected)-Number(b.id===selected)).map(n=>{const p=pos(n.id);if(!p)return null;const isSelected=n.id===selected,active=n.id===lockId,affected=projection.paths.has(n.id),cut=projection.withheld.has(n.id),near=neighbor.has(n.id);const radius=mode==='ratchet'?15:n.type==='claim'?10:['source','theory'].includes(n.type)?13:6;const label=mode==='ratchet'||isSelected||active||(view.z>1.5&&near);return <g key={n.id} transform={`translate(${p.x} ${p.y})`} className={`network-dot ${isSelected?'selected':''} ${active?'current':''} ${affected?'affected':''} ${cut?'withheld':''}`} role="button" tabIndex={0} aria-label={`${n.type}: ${n.title}`} data-node={n.id} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(n.id)}}} onPointerDown={e=>{e.stopPropagation();const mouse=point(e);drag.current={...mouse,id:n.id,ox:p.x,oy:p.y,moving:false};svg.current?.setPointerCapture(e.pointerId);select(n.id)}} style={{'--node-color':colors[n.type]??'#a1b3ca'} as React.CSSProperties}><title>{n.title}</title><circle className="node-halo" r={radius+8}/><circle className="node-core" r={radius}/>{label&&<text y={radius+22} textAnchor="middle">{(n.title??n.id).slice(0,mode==='ratchet'?65:43)}</text>}{active&&<text y={-radius-15} textAnchor="middle" className="current-label">ACTIVE QUESTION</text>}</g>})}
     </g>
    </svg>
    <div className="network-zoom"><button aria-label="Zoom in" onClick={()=>setView(v=>({...v,z:Math.min(4,v.z*1.2)}))}>+</button><button aria-label="Zoom out" onClick={()=>setView(v=>({...v,z:Math.max(.45,v.z/1.2)}))}>−</button><button onClick={()=>{setView({x:0,y:0,z:1});setDragged({})}}>Fit</button><span>Drag nodes · pan background · scroll to zoom</span></div>
    <div className="network-impact-strip"><div><strong>{projection.withheld.size}</strong><span>premises withheld</span></div><div><strong>{changedClaims.length}</strong><span>claims need review</span></div><div><strong>{activeBurdens.filter(id=>!projection.resolved.has(id)).length+projection.hypotheses.length}</strong><span>open obligations</span></div><p>Effects apply to your local walk.<br/>The published record stays intact.</p></div>
   </section>
   <aside className="network-inspector">
    {edgeInfo&&<section><p className="network-kicker">CONNECTION / {edgeInfo.kind}</p><h2>{edgeInfo.label.replaceAll('_',' ')}</h2><p>{nodes.get(edgeInfo.from)?.title} → {nodes.get(edgeInfo.to)?.title}</p><p>{sourceEdge?.rationale??'This connection is a compiled reference or an authored answer branch, not an additional independent source of evidence.'}</p><button onClick={()=>setEdge(undefined)}>Close connection</button></section>}
    {lock&&<section className="network-question"><p className="network-kicker">RATCHET / CURRENT OBLIGATION</p><h2>{lock.question}</h2><div className="network-premises">{(lock.targets??[]).filter((id:string)=>nodes.get(id)?.type==='claim').map((id:string)=><button key={id} onClick={()=>{select(id);setMode('case');setView({x:0,y:0,z:1})}}>Inspect premise: {nodes.get(id)?.title} ↗</button>)}</div><div className="network-response-grid">{GUIDED_RESPONSES.map(response=><button key={response} onClick={()=>{append({kind:'answer',ratchet,lock:lock.id,response});select(response==='tangent'?lock.id:lock.branches[response])}}>{guidedResponseLabels[response]}</button>)}</div><p className="network-small">Answers follow authored branches. They do not certify a claim or erase an obligation. Withhold a premise explicitly below to simulate its loss.</p>{(lock.receipts??[]).map((id:string)=>{const receipt=nodes.get(id);return receipt&&<details key={id}><summary>Receipt · {receipt.title}</summary><blockquote>{receipt.quote??receipt.context}</blockquote><NodeLink node={receipt}>Inspect preserved source →</NodeLink></details>})}</section>}
    <section><p className="network-kicker">SELECTED NODE</p><TypeBadge type={selectedNode.type}/><h2>{selectedNode.title}</h2><p>{selectedNode.statement??selectedNode.question??selectedNode.summary}</p><NodeLink node={selectedNode}>Full record & provenance ↗</NodeLink><div className="network-actions">{!['lock','ratchet','burden','escape','diagnostic'].includes(selectedNode.type)&&<button className="cut-button" onClick={()=>append({kind:projection.withheld.has(selected)?'restore':'withhold',node:selected})}>{projection.withheld.has(selected)?'Restore this premise':'Withhold this premise'}</button>}{relatedRatchets.map(n=><button key={n.id} onClick={()=>launch(n.id)}>Examine: {n.title} →</button>)}</div>
     {projection.paths.has(selected)&&<div className="network-path"><strong>{projection.withheld.has(selected)?'Withheld in this walk':'Dependency affected — review required'}</strong>{projection.paths.get(selected)!.map(id=><button key={id} onClick={()=>select(id)}>{nodes.get(id)?.title} →</button>)}</div>}
     {support&&<div className="network-support"><h3>Recorded support routes</h3><p>{support.intact.length} unaffected · {support.affected.length} affected by this walk</p>{[...support.intact,...support.affected].map(id=><button key={id} onClick={()=>select(id)}>{projection.paths.has(id)?'◌':'●'} {nodes.get(id)?.title??id}</button>)}<small>Unaffected does not mean sufficient or independent. An affected dependency does not prove the conclusion false.</small></div>}
    </section>
    {activeBurdens.length>0&&<section><p className="network-kicker">OBLIGATIONS THAT CARRY FORWARD</p>{activeBurdens.map(id=><div className="network-burden" key={id}><button onClick={()=>select(id)}>{projection.resolved.has(id)?'✓':'○'} {nodes.get(id)?.title}</button>{projection.resolved.has(id)?<p>Locally marked satisfied: {projection.resolved.get(id)}</p>:<button className="network-small" disabled={!note.trim()} onClick={()=>{append({kind:'resolve',node:id,text:note.trim()});setNote('')}}>Mark satisfied using note below</button>}</div>)}<p className="network-small">Satisfaction is your recorded assessment, never automatic verification.</p></section>}
    {projection.callbacks.length>0&&<section className="network-callback"><h3>Earlier answers still matter</h3>{projection.callbacks.map((c,i)=><p key={i}>{c}</p>)}</section>}
    {projection.hypotheses.length>0&&<section className="network-callback"><h3>New explanations carry new obligations</h3>{projection.hypotheses.map((e,i)=><p key={i}>{'text' in e?e.text:''}<br/><strong>Evidence required.</strong> This proposed explanation has not discharged any existing burden.</p>)}</section>}{!!r&&<section><h3>Connected examinations</h3>{(bundle.topology.ratchets[r.id]?.cross_ratchet_callbacks??[]).map((id:string)=>nodes.get(id)?.type==='ratchet'?<button key={id} onClick={()=>launch(id)}>{nodes.get(id)?.title} ↗</button>:<p key={id}>{nodes.get(id)?.title}</p>)}</section>}
    <section><h3>Evidence, qualification, or tangent</h3><textarea aria-label="Walk note" placeholder="Record why, or park another issue…" maxLength={4000} value={note} onChange={e=>setNote(e.target.value)}/><button disabled={!note.trim()} onClick={()=>{append({kind:'note',text:note.trim(),lock:lock?.id});setNote('')}}>Park note · keep current question</button><button disabled={!note.trim()} onClick={()=>{append({kind:'hypothesis',text:note.trim(),lock:lock?.id});setNote('')}}>Propose explanation + evidence obligation</button></section>
   </aside>
  </div>
  <section className="network-trail"><div><p className="network-kicker">YOUR WALK / {events.length} EVENTS</p><button disabled={!events.length} onClick={()=>setEvents(v=>v.slice(0,-1))}>Undo last step</button><a href={href('/guided')}>Classic guided pages ↗</a></div><ol>{events.length?events.map((e,i)=><li key={i}><span>{String(i+1).padStart(2,'0')}</span><strong>{e.kind==='answer'?e.response.replaceAll('_',' '):e.kind}</strong><small>{e.kind==='answer'?nodes.get(e.lock)?.title:e.kind==='note'||e.kind==='hypothesis'?e.text:e.kind==='resolve'?nodes.get(e.node)?.title:'node' in e?nodes.get(e.node)?.title:''}</small></li>):<li className="network-trail-empty">Choose an examination or select a node. Your path will remain visible here.</li>}</ol></section>
 </main>;
}
