import {useState} from 'react';
import type {DataBundle,NodeRecord} from './types';
import {indexBundle} from './data';
import {href} from './router';
import {NodeLink,Section,StateBadge,TypeBadge} from './ui';
import {guidedDomain,primaryClaimsForRatchet,ratchetsForClaim} from '../guided/runtime';

export function Home({bundle}:{bundle:DataBundle}){
 const {nodes}=indexBundle(bundle); const counts=new Map<string,number>();for(const n of bundle.graph.nodes)counts.set(n.type,(counts.get(n.type)??0)+1);
 const top=bundle.order.baseline_order.slice(0,6);
 return <main className="page"><section className="home-hero"><p className="kicker">Debunker · self-guided claim interrogation</p><h1>Don’t just read the rebuttal. Walk the argument.</h1><p className="lede">Pick a published claim, inspect the preserved evidence, choose the strongest response, and follow what that response actually changes. Every guided path is generated from the same provenance-preserving case graph used for technical inspection.</p><div className="button-row"><a className="button guided-primary" href={href('/guided')}>Start a guided case</a><a className="button button-ghost" href={href('/claims')}>Browse claims</a></div></section>
 <div className="stat-grid">{['claim','receipt','burden','ratchet','diagnostic','source'].map(t=><div className="stat-card" key={t}><strong>{counts.get(t)??0}</strong><span>{t}s</span></div>)}</div>
 <Section title="One case, three depths"><div className="three-col prose-cards"><div><h3>GUIDED</h3><p>Plain-language walkthroughs for normal visitors. One claim, one question at a time, with both sides of each branch available.</p><a href={href('/guided')}>Start guided →</a></div><div><h3>EXPLORE</h3><p>Open any claim or receipt directly. Follow WHY? upstream and WHAT DEPENDS ON THIS? downstream.</p><a href={href('/claims')}>Browse case →</a></div><div><h3>TECHNICAL</h3><p>Inspect the full semantic graph, ratchet topology, diagnostics, derivations, and dependency blast radius.</p><a href={href('/graph')}>Open graph →</a></div></div></Section>
 <Section title="Guided examinations" aside={<a href={href('/guided')}>View all</a>}><div className="guided-home-grid">{top.map((o:any)=>{const r=nodes.get(o.ratchet);if(!r)return null;const targets=primaryClaimsForRatchet(bundle,r.id);return <a href={href(`/guided/${r.id}`)} key={r.id}><span className="position">{o.position}</span><div><small>{guidedDomain(r)}</small><strong>{r.title}</strong><p>{targets[0]?.statement??r.summary}</p></div></a>})}</div><p className="footnote">The displayed order is structural only: downstream reach, reviewed diagnostics, trigger breadth, and convergence burdens. It is not a truth or credibility ranking.</p></Section>
 <Section title="What makes this different"><div className="three-col prose-cards"><div><h3>Challenge the claim</h3><p>The source claim is preserved separately from our criticism. Corrections do not erase the original record.</p></div><div><h3>Challenge the criticism</h3><p>Choose the strongest alternative response. A missing branch can be added rather than treated as a defeat of the method.</p></div><div><h3>See what survives</h3><p>Removing one support path does not automatically erase a conclusion. Other support and inherited burdens stay visible.</p></div></div></Section>
 <div className="notice"><strong>Reading rule:</strong> structural problems change what an argument has established; they do not automatically tell you what is true.</div>
 <p className="buildline">Build <code>{bundle.graph.build_id.slice(0,12)}</code> · graph schema {bundle.graph.schema_version}</p></main>
}

function textOf(n:NodeRecord){return `${n.id} ${n.title??''} ${n.summary??''} ${n.statement??''} ${n.question??''} ${n.quote??''} ${(n.tags??[]).join(' ')}`.toLowerCase()}
export function SearchPage({bundle,initial=''}:{bundle:DataBundle;initial?:string}){const [q,setQ]=useState(initial);const rows=q.trim()?bundle.graph.nodes.filter(n=>textOf(n).includes(q.toLowerCase())).slice(0,100):[];return <main className="page"><header className="page-head"><p className="kicker">Search</p><h1>Search the published graph</h1></header><input className="big-search" autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Claim, phrase, ID, tag…"/>{q&&<p className="muted">{rows.length} displayed result{rows.length===1?'':'s'}</p>}<div className="search-results">{rows.map(n=><NodeLink node={n} key={n.id} className="search-result"><TypeBadge type={n.type}/><span><strong>{n.title??n.id}</strong><small>{n.statement??n.summary}</small><code>{n.id}</code></span></NodeLink>)}</div></main>}

export function ClaimsPage({bundle}:{bundle:DataBundle}){const claims=bundle.graph.nodes.filter(n=>n.type==='claim').sort((a,b)=>(a.title??a.id).localeCompare(b.title??b.id));return <main className="page"><header className="page-head"><p className="kicker">Claims</p><h1>Atomic attributed propositions</h1><p className="lede">Open a claim to inspect its source, support, burdens, dependencies, and any self-guided examinations that target it.</p></header><div className="card-list">{claims.map(n=>{const s=bundle.topology.claim_state[n.id];const guided=ratchetsForClaim(bundle,n.id);return <article key={n.id} className="claim-row claim-row-card"><div><TypeBadge type="claim"/><h2><a href={href(`/claim/${n.id}`)}>{n.title}</a></h2><p>{n.statement}</p><div className="button-row compact-buttons"><a className="button button-ghost" href={href(`/claim/${n.id}`)}>Open record</a>{guided[0]&&<a className="button" href={href(`/guided/${guided[0].id}`)}>Examine this claim</a>}{guided.length>1&&<span className="muted small">+{guided.length-1} more walkthrough{guided.length-1===1?'':'s'}</span>}</div></div><div className="right-state"><StateBadge tone={s?.structural_state==='burdened'?'warn':'good'}>{s?.structural_state??'unscored'}</StateBadge><small>{s?.all_burdens?.length??0} burdens</small>{guided.length>0&&<small>{guided.length} guided</small>}</div></article>})}</div></main>}

export function SourcesPage({bundle}:{bundle:DataBundle}){const sources=bundle.graph.nodes.filter(n=>n.type==='source');return <main className="page"><header className="page-head"><p className="kicker">Evidence</p><h1>Preserved evidentiary record</h1><p className="lede">Sources are content-addressed and versioned. Receipts point to precise locations inside them.</p></header><div className="card-list">{sources.map(n=><NodeLink node={n} key={n.id} className="source-row"><TypeBadge type="source"/><div><h2>{n.title}</h2><p>{n.summary}</p><code>{n.id}</code></div></NodeLink>)}</div></main>}

export function DiagnosticsPage({bundle}:{bundle:DataBundle}){const verified=bundle.graph.nodes.filter(n=>n.type==='diagnostic');const candidates=bundle.diagnostics.candidates??[];const {nodes}=indexBundle(bundle);return <main className="page"><header className="page-head"><p className="kicker">Diagnostics</p><h1>Reviewed findings and machine-proposed candidates</h1><p className="lede">Machine candidates never become verified automatically. Reviewed diagnostics still describe structural issues, not automatic truth verdicts.</p></header><Section title="Reviewed diagnostics" aside={<span className="count">{verified.length}</span>}><div className="diagnostic-list">{verified.map(d=><NodeLink node={d} key={d.id} className="diagnostic-card"><div><TypeBadge type="diagnostic"/><StateBadge tone={d.status==='verified'?'good':'warn'}>{d.status}</StateBadge></div><h3>{d.title}</h3><p>{d.statement}</p><small>{d.diagnostic_type?.replaceAll('_',' ')}</small></NodeLink>)}</div></Section><Section title="Machine-proposed audit candidates" aside={<span className="count">{candidates.length}</span>}>{candidates.length?<div className="diagnostic-list">{candidates.map((c:any)=><article className="diagnostic-card candidate" key={c.id}><div><StateBadge tone="warn">machine proposed</StateBadge></div><h3>{c.detector?.replaceAll('_',' ')}</h3><p>{c.explanation??c.message??'Candidate generated by the deterministic audit engine.'}</p><div className="ref-list">{(c.triggering_nodes??[]).map((id:string)=>nodes.get(id)?<NodeLink key={id} node={nodes.get(id)!}/>:<code key={id}>{id}</code>)}</div><code>{c.id}</code></article>)}</div>:<p className="muted">No machine-proposed candidates in this build.</p>}</Section></main>}
