import {useEffect,useMemo,useRef,useState} from 'react';
import type {DataBundle,NodeRecord} from './types';
import {indexBundle} from './data';
import {href} from './router';
import {Empty,NodeLink,Section,StateBadge,TypeBadge} from './ui';
import {
  RESPONSE_KINDS,LocalSessionAdapter,activateLock,activateRatchet,addSessionNote,classifyResponse,
  closeActiveLock,closeActiveRatchet,closeBurden,createSession,endSession,exportSession,formatElapsed,
  loadLocalSession,parkTangent,parseSession,renameSession,replaySession,saveLocalSession,sessionBuildWarning,
  staticRatchetCallbacks,type ResponseKind,type SessionDocument
} from '../session/runtime';

const commitmentTone:Record<string,string>={accepted:'good',rejected:'warn',qualified:'warn',withdrawn:'warn',unanswered:'neutral',parked:'neutral'};
const closureOptions=['burden_satisfied','claim_withdrawn','claim_qualified','contradiction_acknowledged','unresolved'];
function RefList({ids,bundle}:{ids:string[];bundle:DataBundle}){const {nodes}=indexBundle(bundle);if(!ids.length)return <Empty/>;return <div className="ref-list">{ids.map(id=>nodes.get(id)?<NodeLink key={id} node={nodes.get(id)!}/>:<code key={id}>{id}</code>)}</div>}
function SessionMeta({doc,bundle}:{doc:SessionDocument;bundle:DataBundle}){const warning=sessionBuildWarning(doc,bundle);return <>{warning&&<div className="notice"><strong>Build mismatch:</strong> {warning} Replay remains available, but node meanings may have changed.</div>}<div className="session-meta"><span><strong>{doc.session_id}</strong></span><span>graph {doc.graph_build_id.slice(0,12)}</span><span>schema {doc.graph_schema_version}</span><span>{doc.git_commit?`git ${doc.git_commit.slice(0,10)}`:'git commit not injected'}</span></div></>}
export function OperatorPage({bundle}:{bundle:DataBundle}){
  const [doc,setDoc]=useState<SessionDocument|null>(()=>loadLocalSession());
  const [answer,setAnswer]=useState('');const [tangent,setTangent]=useState('');const [tangentTopic,setTangentTopic]=useState('');const [note,setNote]=useState('');
  const [closure,setClosure]=useState('unresolved');const [error,setError]=useState('');const importRef=useRef<HTMLInputElement>(null);
  const {nodes}=useMemo(()=>indexBundle(bundle),[bundle]);
  useEffect(()=>LocalSessionAdapter.subscribe(setDoc),[]);
  const commit=(next:SessionDocument|null)=>{setError('');saveLocalSession(next);setDoc(next)};
  const run=(fn:()=>SessionDocument)=>{try{commit(fn())}catch(e){setError(e instanceof Error?e.message:String(e))}};
  const state=doc?replaySession(doc):null;const activeLock=state?.active_lock_id?nodes.get(state.active_lock_id):undefined;const activeRatchet=state?.active_ratchet_id?nodes.get(state.active_ratchet_id):undefined;
  const ratchets=bundle.order.baseline_order.map((o:any)=>nodes.get(o.ratchet)).filter(Boolean) as NodeRecord[];
  const newSession=()=>{const title=prompt('Session title','Live interrogation')??'Live interrogation';commit(createSession(bundle,title))};
  const importSession=async(f:File)=>{try{const parsed=parseSession(await f.text());commit(parsed)}catch(e){setError(e instanceof Error?e.message:String(e))}};
  const classify=(kind:ResponseKind)=>{if(!doc)return;run(()=>classifyResponse(doc,bundle,kind,answer));if(kind!=='tangent')setAnswer('')};
  return <main className="page operator-page"><header className="page-head"><p className="kicker">Operator console</p><h1>Live interrogation runtime</h1><p className="lede">Local, event-sourced session state. Classify the response, preserve commitments, keep the active burden visible, park tangents, and surface callbacks without rewriting the published graph.</p><div className="button-row"><button className="button" onClick={newSession}>New session</button>{doc&&<><button className="button button-ghost" onClick={()=>exportSession(doc)}>Export JSON</button><a className="button button-ghost" href={href('/replay')}>Replay</a></>}<button className="button button-ghost" onClick={()=>importRef.current?.click()}>Import session</button><input ref={importRef} hidden type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void importSession(f);e.currentTarget.value=''}}/></div></header>
  {error&&<div className="error-box">{error}</div>}
  {!doc?<Section title="No local session"><p>Start a session or import a prior export. The public graph remains unchanged.</p></Section>:<>
    <SessionMeta doc={doc} bundle={bundle}/>
    <div className="operator-summary"><div><strong>{doc.events.length}</strong><span>events</span></div><div><strong>{state!.commitments.size}</strong><span>current commitments</span></div><div><strong>{state!.open_burdens.size}</strong><span>open burdens</span></div><div><strong>{state!.tangents.length}</strong><span>parked tangents</span></div><div><strong>{state!.callbacks.length}</strong><span>callbacks</span></div></div>
    <div className="operator-grid"><section className="operator-main">
      <Section title="Ratchet control" aside={activeRatchet?<StateBadge tone="good">active</StateBadge>:undefined}><div className="ratchet-launch-grid">{ratchets.map(r=><button key={r.id} className={`launch-card ${r.id===activeRatchet?.id?'active':''}`} onClick={()=>run(()=>activateRatchet(doc,bundle,r.id))}><TypeBadge type="ratchet"/><strong>{r.title}</strong><small>{r.id}</small></button>)}</div></Section>
      <Section title="Active Lock" aside={activeLock?<code>{activeLock.id}</code>:undefined}>{activeLock?<><div className="active-lock-question"><div className="eyebrow"><TypeBadge type="lock"/>{activeRatchet&&<StateBadge>{activeRatchet.title}</StateBadge>}</div><h2>{activeLock.title}</h2><p>{activeLock.question}</p></div><div className="two-col"><div><h3>Targets</h3><RefList ids={activeLock.targets??[]} bundle={bundle}/></div><div><h3>Burdens</h3><RefList ids={activeLock.burdens??[]} bundle={bundle}/></div></div><label className="field"><span>Exact answer / transcript excerpt</span><textarea rows={5} value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Paste or type the answer as closely as possible…"/></label><div className="response-buttons">{RESPONSE_KINDS.map(k=><button key={k} className={`response-btn response-${k}`} onClick={()=>classify(k)}>{k.replace('_',' ')}</button>)}</div><div className="closure-row"><label>Lock closure<select value={closure} onChange={e=>setClosure(e.target.value)}>{closureOptions.map(x=><option key={x}>{x}</option>)}</select></label><button className="button button-ghost" onClick={()=>run(()=>closeActiveLock(doc,closure))}>Record closure</button>{activeRatchet&&<button className="button button-ghost" onClick={()=>run(()=>closeActiveRatchet(doc,closure))}>Close ratchet</button>}</div></>:<Empty>Select a ratchet to activate its entry Lock.</Empty>}</Section>
      <Section title="Parking lot"><p className="muted">Parking a tangent never changes the active Lock.</p><label className="field"><span>Tangent / new evidence</span><textarea rows={3} value={tangent} onChange={e=>setTangent(e.target.value)} placeholder="What was raised?"/></label><div className="park-row"><select value={tangentTopic} onChange={e=>setTangentTopic(e.target.value)}><option value="">No linked ratchet</option>{ratchets.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select><button className="button" onClick={()=>{if(!doc)return;run(()=>parkTangent(doc,tangent,tangentTopic||undefined));setTangent('')}}>Park tangent</button></div>{state!.tangents.length>0&&<div className="tangent-list">{state!.tangents.map(t=><article key={t.event_id}><time>{formatElapsed(t.elapsed_ms)}</time><p>{t.text}</p>{t.topic_id&&nodes.get(t.topic_id)&&<NodeLink node={nodes.get(t.topic_id)!}/>}</article>)}</div>}</Section>
      <Section title="Operator note"><div className="park-row"><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Private/local session note…"/><button className="button button-ghost" onClick={()=>{if(!doc)return;run(()=>addSessionNote(doc,note));setNote('')}}>Add note</button></div></Section>
    </section><aside className="operator-side">
      <Section title="Open burdens" aside={<span className="count">{state!.open_burdens.size}</span>}>{state!.open_burdens.size?<div className="burden-runtime-list">{[...state!.open_burdens].map(id=>{const n=nodes.get(id);return <article key={id}><div>{n?<NodeLink node={n}/>:<code>{id}</code>}</div><button className="mini-button" onClick={()=>run(()=>closeBurden(doc,id,'operator_resolved'))}>Mark resolved</button></article>})}</div>:<Empty/>}</Section>
      <Section title="Commitment ledger" aside={<span className="count">{state!.commitments.size}</span>}>{state!.commitments.size?<div className="commitment-list">{[...state!.commitments.values()].sort((a,b)=>b.elapsed_ms-a.elapsed_ms).map(c=>{const n=nodes.get(c.claim_id);return <article key={c.claim_id}><div className="eyebrow"><StateBadge tone={commitmentTone[c.status]??'neutral'}>{c.status}</StateBadge><time>{formatElapsed(c.elapsed_ms)}</time></div>{n?<NodeLink node={n}/>:<code>{c.claim_id}</code>}{c.answer_text&&<blockquote>{c.answer_text}</blockquote>}</article>})}</div>:<Empty/>}</Section>
      <Section title="Callbacks" aside={<span className="count">{state!.callbacks.length}</span>}><>{activeRatchet&&staticRatchetCallbacks(bundle,activeRatchet.id).length>0&&<div className="static-callbacks"><h3>Ratchet callbacks</h3><RefList ids={staticRatchetCallbacks(bundle,activeRatchet.id)} bundle={bundle}/></div>}{state!.callbacks.length?<div className="callback-list">{state!.callbacks.map(c=><article key={c.event_id}><StateBadge tone="warn">callback</StateBadge><p>{c.message}</p>{c.edge_id&&<code>{c.edge_id}</code>}<time>{formatElapsed(c.elapsed_ms)}</time></article>)}</div>:<Empty/>}</></Section>
      <Section title="Session"><label className="field"><span>Title</span><input value={doc.title} onChange={e=>commit(renameSession(doc,e.target.value))}/></label><div className="button-row"><button className="button button-ghost" onClick={()=>run(()=>endSession(doc))} disabled={state!.status==='ended'}>End session</button><button className="button danger" onClick={()=>{if(confirm('Clear the local operator session? Export first if you need it.'))commit(null)}}>Clear local</button></div><p className="footnote">Operator state is stored in this browser only until exported or connected to a future realtime adapter.</p></Section>
    </aside></div>
    <Section title="Event stream" aside={<span className="count">{doc.events.length}</span>}><div className="event-stream">{[...doc.events].reverse().map(e=><article key={e.event_id}><time>{formatElapsed(e.elapsed_ms)}</time><span className="event-type">{e.event_type.replaceAll('_',' ')}</span><p>{eventSummary(e,bundle)}</p><code>{e.event_id}</code></article>)}</div></Section>
  </>}</main>
}
function eventSummary(e:any,bundle:DataBundle){const n=(id:string)=>bundle.graph.nodes.find(x=>x.id===id)?.title??id;const p=e.payload;switch(e.event_type){case'session_started':return p.title;case'ratchet_activated':return n(p.ratchet_id);case'lock_activated':return n(p.lock_id);case'response_classified':return `${String(p.response).replaceAll('_',' ')}${p.answer_text?`: ${p.answer_text}`:''}`;case'commitment_added':return `${p.status}: ${n(p.claim_id)}`;case'burden_opened':return n(p.burden_id);case'burden_closed':return `${n(p.burden_id)} — ${p.resolution}`;case'tangent_parked':return p.text;case'callback_available':return p.message;case'lock_closed':return `${n(p.lock_id)} — ${p.closure}`;case'ratchet_closed':return `${n(p.ratchet_id)} — ${p.closure}`;case'note_added':return p.text;case'session_ended':return p.note||'Session ended';default:return e.event_type}}
