import {useEffect,useRef,useState} from 'react';
import type {DataBundle} from './types';
import {indexBundle} from './data';
import {href} from './router';
import {Empty,NodeLink,Section,StateBadge,TypeBadge} from './ui';
import {LocalSessionAdapter,formatElapsed,loadLocalSession,parseSession,replaySession,sessionBuildWarning,type SessionDocument} from '../session/runtime';

export function ReplayPage({bundle}:{bundle:DataBundle}){
  const [doc,setDoc]=useState<SessionDocument|null>(()=>loadLocalSession());const [step,setStep]=useState<number>(()=>loadLocalSession()?.events.length??0);const [error,setError]=useState('');const fileRef=useRef<HTMLInputElement>(null);const {nodes}=indexBundle(bundle);
  useEffect(()=>LocalSessionAdapter.subscribe(d=>{setDoc(d);setStep(d?.events.length??0)}),[]);
  const importReplay=async(f:File)=>{try{const d=parseSession(await f.text());setDoc(d);setStep(d.events.length);setError('')}catch(e){setError(e instanceof Error?e.message:String(e))}};
  if(!doc)return <main className="page"><header className="page-head"><p className="kicker">Session replay</p><h1>Replay an interrogation</h1><p className="lede">Load the current local operator session or import an exported session JSON.</p></header>{error&&<div className="error-box">{error}</div>}<button className="button" onClick={()=>fileRef.current?.click()}>Import session JSON</button><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void importReplay(f)}}/></main>;
  const state=replaySession(doc,step);const activeLock=state.active_lock_id?nodes.get(state.active_lock_id):undefined;const warning=sessionBuildWarning(doc,bundle);const event=step>0?doc.events[step-1]:undefined;
  return <main className="page replay-page"><header className="page-head"><p className="kicker">Session replay</p><h1>{doc.title}</h1><p className="lede">Replay is derived from the immutable event stream. Moving the scrubber reconstructs commitments, burdens, callbacks, tangents, and the active Lock at that exact point.</p><div className="button-row"><a className="button button-ghost" href={href('/operator')}>Open operator</a><button className="button button-ghost" onClick={()=>fileRef.current?.click()}>Import another session</button><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void importReplay(f)}}/></div></header>
  {warning&&<div className="notice"><strong>Historical build:</strong> {warning}</div>}{error&&<div className="error-box">{error}</div>}
  <section className="replay-control"><button onClick={()=>setStep(0)} disabled={!step}>|◀</button><button onClick={()=>setStep(Math.max(0,step-1))} disabled={!step}>◀</button><input type="range" min={0} max={doc.events.length} value={step} onChange={e=>setStep(Number(e.target.value))}/><button onClick={()=>setStep(Math.min(doc.events.length,step+1))} disabled={step>=doc.events.length}>▶</button><button onClick={()=>setStep(doc.events.length)} disabled={step>=doc.events.length}>▶|</button><span><strong>{step}</strong> / {doc.events.length}</span>{event&&<time>{formatElapsed(event.elapsed_ms)}</time>}</section>
  <div className="replay-state-grid"><Section title="Active Lock">{activeLock?<><div className="eyebrow"><TypeBadge type="lock"/><code>{activeLock.id}</code></div><h2>{activeLock.title}</h2><p className="question">{activeLock.question}</p></>:<Empty/>}</Section><Section title="Current state"><div className="replay-stats"><span><strong>{state.commitments.size}</strong> commitments</span><span><strong>{state.open_burdens.size}</strong> burdens</span><span><strong>{state.tangents.length}</strong> tangents</span><span><strong>{state.callbacks.length}</strong> callbacks</span></div>{state.active_ratchet_id&&nodes.get(state.active_ratchet_id)&&<NodeLink node={nodes.get(state.active_ratchet_id)!}/>}</Section></div>
  <div className="three-col replay-columns"><Section title="Commitments">{state.commitments.size?<div className="commitment-list">{[...state.commitments.values()].map(c=><article key={c.claim_id}><StateBadge tone={['accepted'].includes(c.status)?'good':'warn'}>{c.status}</StateBadge>{nodes.get(c.claim_id)?<NodeLink node={nodes.get(c.claim_id)!}/>:<code>{c.claim_id}</code>}{c.answer_text&&<blockquote>{c.answer_text}</blockquote>}</article>)}</div>:<Empty/>}</Section><Section title="Open burdens">{state.open_burdens.size?<div className="ref-list">{[...state.open_burdens].map(id=>nodes.get(id)?<NodeLink key={id} node={nodes.get(id)!}/>:<code key={id}>{id}</code>)}</div>:<Empty/>}</Section><Section title="Parking lot">{state.tangents.length?<div className="tangent-list">{state.tangents.map(t=><article key={t.event_id}><time>{formatElapsed(t.elapsed_ms)}</time><p>{t.text}</p></article>)}</div>:<Empty/>}</Section></div>
  <Section title="Callbacks">{state.callbacks.length?<div className="callback-list">{state.callbacks.map(c=><article key={c.event_id}><StateBadge tone="warn">callback</StateBadge><p>{c.message}</p><time>{formatElapsed(c.elapsed_ms)}</time></article>)}</div>:<Empty/>}</Section>
  <Section title="Timeline"><div className="event-stream replay-events">{doc.events.map(e=><button key={e.event_id} className={e.sequence===step?'current':''} onClick={()=>setStep(e.sequence)}><time>{formatElapsed(e.elapsed_ms)}</time><span>{e.sequence}</span><strong>{e.event_type.replaceAll('_',' ')}</strong><small>{summarize(e,bundle)}</small></button>)}</div></Section>
  <p className="buildline">Recorded against graph <code>{doc.graph_build_id.slice(0,12)}</code> · schema {doc.graph_schema_version}</p></main>
}
function summarize(e:any,bundle:DataBundle){const n=(id:string)=>bundle.graph.nodes.find(x=>x.id===id)?.title??id;const p=e.payload;switch(e.event_type){case'ratchet_activated':return n(p.ratchet_id);case'lock_activated':return n(p.lock_id);case'response_classified':return `${p.response}${p.answer_text?` · ${p.answer_text}`:''}`;case'commitment_added':return `${p.status} · ${n(p.claim_id)}`;case'burden_opened':case'burden_closed':return n(p.burden_id);case'tangent_parked':return p.text;case'callback_available':return p.message;case'note_added':return p.text;default:return p.title??p.closure??''}}
