const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.argv[2]||'http://127.0.0.1:5173/';const out=path.resolve('network-evidence',process.argv[3]||'dev');fs.mkdirSync(out,{recursive:true});
const graph=JSON.parse(fs.readFileSync('dist-data/graph.json','utf8'));const nodes=new Map(graph.nodes.map(n=>[n.id,n]));
const report={base,checks:[],errors:[],http_errors:[]};
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH,headless:true});const context=await browser.newContext({viewport:{width:1680,height:1050}});const page=await context.newPage();page.setDefaultTimeout(25000);page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)report.http_errors.push(r.url())});
const pass=name=>{report.checks.push(name);console.log('PASS',name)};const shot=async name=>page.screenshot({path:path.join(out,name+'.png'),fullPage:true,timeout:60000});
const select=async id=>{await page.getByLabel('Find a graph node').fill(id);await page.locator('.network-results button').first().click()};
try{
 await page.goto(base);await page.locator('.network-dot').first().waitFor();assert.equal(await page.locator('.network-dot').count(),249);await shot('network');pass('full compiled network renders');
 const dot=page.locator('[data-node="clm-petn-shaped-charge-hidden"]');const before=await dot.getAttribute('transform');const box=await dot.locator('.node-core').boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+55,box.y+35,{steps:8});await page.mouse.up();assert.notEqual(await dot.getAttribute('transform'),before);await page.getByRole('button',{name:'Zoom in',exact:true}).click();await page.getByRole('button',{name:'Fit',exact:true}).click();pass('node dragging, zoom and fit');
 await select('clm-4940-strouhal');await page.getByRole('button',{name:'Withhold this premise',exact:true}).click();await select('clm-4940-ballistic-gel');assert.match(await page.locator('.network-support').innerText(),/1 unaffected · 1 affected/);assert.ok(await page.locator('.network-path button').count()>=2);await shot('affected-support');pass('withdrawal traces dependency and preserves alternate support');
 await select('clm-4940-cavitation-confirmation');await page.getByRole('button',{name:'Withhold this premise',exact:true}).click();await select('clm-4940-ballistic-gel');assert.match(await page.locator('.network-support').innerText(),/0 unaffected · 2 affected/);await page.reload();await page.locator('.network-dot').first().waitFor();await select('clm-4940-ballistic-gel');assert.match(await page.locator('.network-support').innerText(),/0 unaffected · 2 affected/);await page.getByRole('button',{name:'Undo last step',exact:true}).click();assert.match(await page.locator('.network-support').innerText(),/1 unaffected · 1 affected/);pass('cumulative simulation, refresh persistence and undo');
 await page.getByRole('button',{name:'Reset walk',exact:true}).click();
 const ratchets=['rat-itd-nearfield','rat-4940-provenance','rat-pcb-dimensions','rat-pcb-color','rat-radial-pressure','rat-13of13-meaning'];
 for(const id of ratchets){await page.getByLabel('Choose a ratchet').selectOption(id);const entry=nodes.get(nodes.get(id).entry_lock);assert.equal(await page.locator('.network-question h2').innerText(),entry.question);
  for(const response of ['yes','no','tangent']){await page.locator('.network-response-grid button').nth(['yes','no','qualify','unknown','withdraw','non_answer','tangent'].indexOf(response)).click();const next=response==='tangent'?entry.id:entry.branches[response];assert.equal(await page.locator('.network-question h2').innerText(),nodes.get(next).question);assert.ok(await page.locator('.network-burden').count()>0);await page.getByRole('button',{name:'Undo last step',exact:true}).click();assert.equal(await page.locator('.network-question h2').innerText(),entry.question)}
  pass('authored yes/no/tangent paths and retained burden: '+id);
 }
 await page.getByLabel('Choose a ratchet').selectOption('rat-pcb-color');await page.locator('.network-response-grid button').first().click();const question=await page.locator('.network-question h2').innerText();await page.reload();await page.locator('.network-question').waitFor();assert.equal(await page.locator('.network-question h2').innerText(),question);assert.ok(await page.locator('.network-edge.taken').count()>0);await page.locator('.network-response-grid button').first().click();await page.locator('.network-response-grid button').nth(1).click();assert.match(await page.locator('.network-callback').first().innerText(),/Revisited/);pass('ratchet resume, visible taken path and earlier-answer callback');
 await page.getByLabel('Walk note').fill('Hypothetical mount shielding');await page.getByRole('button',{name:'Propose explanation + evidence obligation',exact:true}).click();assert.match(await page.locator('.network-inspector').innerText(),/Evidence required/);assert.equal(await page.locator('.network-question h2').innerText(),question);pass('new explanation adds evidence obligation without discharging existing burden');
 await page.getByLabel('Walk note').fill('Local assessment for browser test');await page.getByRole('button',{name:'Mark satisfied using note below'}).first().click();assert.match(await page.locator('.network-burden').first().innerText(),/Locally marked satisfied/);await shot('ratchet');pass('explicit local burden resolution retains explanation');
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export',exact:true}).click();const download=await downloadPromise;const file=path.join(out,'walk.json');await download.saveAs(file);const saved=JSON.parse(fs.readFileSync(file));await page.getByRole('button',{name:'Reset walk',exact:true}).click();await page.locator('input[type=file]').setInputFiles(file);await page.waitForFunction(expected=>document.querySelectorAll('.network-trail li').length===expected,saved.events.length);assert.equal(await page.locator('.network-trail li').count(),saved.events.length);pass('walk export and import');
 await page.locator('input[type=file]').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"build":"foreign","events":[]}')});await page.getByRole('alert').waitFor();assert.match(await page.getByRole('alert').innerText(),/invalid|different/);assert.equal(await page.locator('.network-trail li').count(),saved.events.length);pass('foreign build import fails without replacing state');
 await page.getByRole('button',{name:'Reset walk',exact:true}).click();await page.getByRole('button',{name:'Case network',exact:true}).click();await page.setViewportSize({width:390,height:844});await shot('mobile');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));pass('mobile layout fits viewport');
 await page.goto(base+'#/claim/clm-itd-nearfield-only');await page.getByRole('heading',{name:'WHY?',exact:true}).waitFor();await page.getByRole('link',{name:'Open in graph',exact:true}).click();await page.locator('.network-dot').first().waitFor();assert.match(await page.locator('.network-inspector').innerText(),/113.4/);pass('existing record links open the graph with selected node');
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.http_errors,[]);pass('zero console, runtime and HTTP errors');report.status='passed';
}catch(e){report.status='failed';report.error=e.stack;console.error(e);await shot('failure');process.exitCode=1}finally{fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
